image: mcr.microsoft.com/playwright/python:v1.57.0-jammy

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

playwright_tests:
  stage: test
  script:
    - pytest -v
  artifacts:
    when: always
    paths:
      - reports/
      - allure-results/
    expire_in: 7 days
