image: mcr.microsoft.com/playwright/python:v1.57.0-jammy

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DB_HOST: $DB_HOST
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD
  DB_PORT: $DB_PORT

cache:
  paths:
    - .cache/pip

before_script:
  # - python --version
  # - pip install --upgrade pip
  # - pip install -r requirements.txt

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - playwright install --with-deps
  - mkdir -p reports

  # Save SSH private key passed from GitLab CI env
  - echo "$SSH_PKEY" > /tmp/ci_ssh_key.pem
  - chmod 600 /tmp/ci_ssh_key.pem

playwright_tests:
  stage: test
  script:
    - pytest -v
  artifacts:
    when: always
    paths:
      - reports/
      - allure-results/
    expire_in: 7 days
